### ISSUE TITLE
comment not clear 

### ISSUE THREAD

**Issue by moab374a** [CU1KNIGHT/inf120#15]
**Describe the bug**
A comment you did wrote it but it seems to be not very clear 

**To Reproduce**
1. Go to 'v4' line 6 and 7

**Expected behavior**
 write more Details about the missing Beispiel so I can easily located and correct it
where should it be ? 
existed or not ? wenn existed , incomplete or wrong written ?     

:)

**Comment by CU1KNIGHT** [comment]
line in code?
with screenshot?

**Comment by CU1KNIGHT** [comment]
ive started to write at 4.3 beispiel with " 1/k ist divergent , denn lim..."

**Comment by moab374a** [comment]
![Screen shot](https://user-images.githubusercontent.com/44247875/56473283-28c73b80-6469-11e9-9296-eb01972c3279.jpg)

line in code 6 and 7 in V4

**Comment by CU1KNIGHT** [comment]
Du hast geschrieben es ist Beispiel 4.1

**Comment by CU1KNIGHT** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/24196708/56473322-0681ed80-646a-11e9-86e2-c20b2e1a34e3.png)

**Comment by CU1KNIGHT** [comment]
i will closed as resolved
