### ISSUE TITLE
N+1 in index

### ISSUE THREAD

**Issue by CU1KNIGHT** [CU1KNIGHT/inf120#16]
**Describe the bug**

**To Reproduce**
1. Go to '1.38 Beispiel'
3. Scroll down to 'lim Xn+1'

**Expected 
X (n+1) as index

**Screenshots**
.
![15561255883607060564550996054906](https://user-images.githubusercontent.com/24196708/56678922-1b59bd80-66c4-11e9-87c5-eb26926bc5b7.jpg)

**Comment by moab374a** [comment]
Done X_n+1 is now X_{(n+1)}
