### ISSUE TITLE
Readme typos 

### ISSUE THREAD

**Issue by bahamasbahamas** [CU1KNIGHT/inf120#33]
Wir erstellen hier eine Mitschrift für die Vorlesung INF-120 (Mathe) des Sommersemesters 2019 an der Technischen Universität Dresden. 

Wenn du Fehler im Skript findest, erstelle bitte ein Issue.

Liebe Grüße
Mahmoud Kiki
Abdelshafi Mohamed

**Comment by CU1KNIGHT** [comment]
Vielen dank für deine Meldung
es wird korrigiert.
